package model;
// Generated Oct 24, 2020 11:56:23 PM by Hibernate Tools 4.3.1


import controller.adminController;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;

/**
 * Admin generated by hbm2java
 */
@ManagedBean
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String username;
     private String password;
     private Set newses = new HashSet(0);

    public Admin() {
    }

	
    public Admin(String name, String username, String password) {
        this.name = name;
        this.username = username;
        this.password = password;
    }
    public Admin(String name, String username, String password, Set newses) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.newses = newses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getNewses() {
        return this.newses;
    }
    
    public void setNewses(Set newses) {
        this.newses = newses;
    }

    public String validatelogin()
    { 
        try {
            adminController controller = new adminController();
            List<Admin> admin=controller.validateLogin(username, password);
            username=admin.get(0).username;
            password=admin.get(0).password;
            name=admin.get(0).name;
            id=admin.get(0).id;
            
            FacesContext context = FacesContext.getCurrentInstance();
            if(username != null) {
                context.getExternalContext().getSessionMap().put("username", username);
                context.getExternalContext().getSessionMap().put("name", name);
                context.getExternalContext().getSessionMap().put("id", id);
                return "success";
            }
            else {
                return "error";
            }
        }
        catch(Exception ex) {
            return "error";
        }
    }
    
    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "index";
    }


}


