package model;
// Generated Oct 24, 2020 11:56:23 PM by Hibernate Tools 4.3.1

import controller.adminController;
import controller.creatorController;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;

/**
 * Stickers generated by hbm2java
 */
@ManagedBean
public class Stickers implements java.io.Serializable {

    private int id;
    private Integer creators;
    private String name;
    private String url;
    private int price;
    private Set transactionses = new HashSet(0);

    public Stickers() {
    }

    public Stickers(int id, Integer creators, String name, String url, int price) {
        this.id = id;
        this.creators = creators;
        this.name = name;
        this.url = url;
        this.price = price;
    }

    public Stickers(int id, Integer creators, String name, String url, int price, Set transactionses) {
        this.id = id;
        this.creators = creators;
        this.name = name;
        this.url = url;
        this.price = price;
        this.transactionses = transactionses;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Integer getCreators() {
        return this.creators;
    }

    public void setCreators(Integer creators) {
        this.creators = creators;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public int getPrice() {
        return this.price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public Set getTransactionses() {
        return this.transactionses;
    }

    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }

    public void save() {
        creatorController controller = new creatorController();
        controller.inputStickers(this);
    }

    public List<SelectItem> getAllCreators() {
        List<SelectItem> creators = new ArrayList<>();
        creatorController controller = new creatorController();
        List<Creators> creatorID = controller.retrieveCreators();
        for (Creators kode : creatorID) {
            creators.add(new SelectItem(kode.getId(), kode.getUsername()));
        }
        return creators;
    }

}
