package model;
// Generated Oct 24, 2020 11:56:23 PM by Hibernate Tools 4.3.1



/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private Integer id;
     private Stickers stickers;
     private Users users;
     private int totalprice;

    public Transactions() {
    }

    public Transactions(Stickers stickers, Users users, int totalprice) {
       this.stickers = stickers;
       this.users = users;
       this.totalprice = totalprice;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Stickers getStickers() {
        return this.stickers;
    }
    
    public void setStickers(Stickers stickers) {
        this.stickers = stickers;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getTotalprice() {
        return this.totalprice;
    }
    
    public void setTotalprice(int totalprice) {
        this.totalprice = totalprice;
    }




}


