package model;
// Generated Oct 24, 2020 11:56:23 PM by Hibernate Tools 4.3.1


import controller.adminController;
import controller.usersController;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;

@ManagedBean
/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String address;
     private String email;
     private String phone;
     private String username;
     private String password;
     private Set transactionses = new HashSet(0);

    public Users() {
    }

	
    public Users(String firstName, String lastName, String address, String email, String phone, String username, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.email = email;
        this.phone = phone;
        this.username = username;
        this.password = password;
    }
    public Users(String firstName, String lastName, String address, String email, String phone, String username, String password, Set transactionses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.email = email;
       this.phone = phone;
       this.username = username;
       this.password = password;
       this.transactionses = transactionses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }

    public String validatelogin()
    { 
        try {
            usersController controller = new usersController();
            List<Users> users=controller.validateLogin(username, password);
            username=users.get(0).username;
            password=users.get(0).password;
            id=users.get(0).id;
            
            FacesContext context = FacesContext.getCurrentInstance();
            if(username != null) {
                context.getExternalContext().getSessionMap().put("username", username);
                context.getExternalContext().getSessionMap().put("email", email);
                return "success";
            }
            else {
                return "error";
            }
        }
        catch(Exception ex) {
            return "error";
        }
    }
    
    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "index";
    }
    
    public void update() {
        usersController controller = new usersController();
        controller.updateUsers(this);
    }
    
    public List<Users> readUsers() {
        usersController controller = new usersController();
        List<Users> readusers = controller.readUsers(id);
        return readusers;
    }
    
    public List<Users> getbyemail(String email) {
        usersController controller = new usersController();
        List<Users> users = controller.getbyemail(email);
        firstName = users.get(0).firstName;
        lastName = users.get(0).lastName;
        return users;
    }
    
    public List<Users> getbyusername() {
        usersController controller = new usersController();
        List<Users> searchUsername = controller.getByUsername(username); //Class yang ada di DAO/CONTROLLER
        id = searchUsername.get(0).id;
        firstName = searchUsername.get(0).firstName;
        lastName = searchUsername.get(0).lastName;
        address = searchUsername.get(0).address;
        email = searchUsername.get(0).email;
        phone = searchUsername.get(0).phone;
        username = searchUsername.get(0).username;
        password = searchUsername.get(0).password;
        return searchUsername;
    }
    
    public List<Users> getbyid() {
        usersController controller = new usersController();
        List<Users> users = controller.getbyID(id);
        firstName = users.get(0).firstName;
        lastName = users.get(0).lastName;
        address = users.get(0).address;
        email = users.get(0).email;
        phone = users.get(0).phone;
        username = users.get(0).username;
        password = users.get(0).password;
        return users;
    }
    
    public void delete() {
        adminController controller = new adminController();
        controller.deleteUsers(id);
    }
}


